# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-23 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artista', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='artista',
            table='artista',
        ),
    ]
